// ─── FIFA World Cup 2026™ — TactixIQ Scout Data ──────────────────────────────
// Real squads, real groups, real results. Tournament: Jun 11 – Jul 19, 2026
// Hosted by: USA, Canada, Mexico | 48 teams | 104 matches

// ─── Groups ───────────────────────────────────────────────────────────────────

export const GROUPS = {
  A: { teams: ['Mexico', 'South Africa', 'South Korea', 'Czechia'], host: 'Mexico' },
  B: { teams: ['Canada', 'Bosnia & Herzegovina', 'Qatar', 'Switzerland'], host: 'Canada' },
  C: { teams: ['Brazil', 'Haiti', 'Morocco', 'Scotland'] },
  D: { teams: ['USA', 'Paraguay', 'Australia', 'Türkiye'], host: 'USA' },
  E: { teams: ['Germany', 'Curaçao', 'Ivory Coast', 'Ecuador'] },
  F: { teams: ['Netherlands', 'Japan', 'Sweden', 'Tunisia'] },
  G: { teams: ['Belgium', 'Egypt', 'Iran', 'New Zealand'] },
  H: { teams: ['Spain', 'Cape Verde', 'Saudi Arabia', 'Uruguay'] },
  I: { teams: ['France', 'Iraq', 'Norway', 'Senegal'] },
  J: { teams: ['Argentina', 'Algeria', 'Austria', 'Jordan'] },
  K: { teams: ['Colombia', 'DR Congo', 'Portugal', 'Uzbekistan'] },
  L: { teams: ['Croatia', 'England', 'Ghana', 'Panama'] },
}

// ─── Match Results (updated live) ─────────────────────────────────────────────

export const RESULTS = [
  { date: 'Jun 11', group: 'A', home: 'Mexico',       away: 'South Africa',          score: '2-0', venue: 'Mexico City Stadium', status: 'FT' },
  { date: 'Jun 12', group: 'A', home: 'South Korea',  away: 'Czechia',               score: '2-1', venue: 'Guadalajara Stadium', status: 'FT' },
  { date: 'Jun 12', group: 'B', home: 'Canada',       away: 'Bosnia & Herzegovina',  score: '1-1', venue: 'Toronto Stadium',     status: 'FT' },
  { date: 'Jun 12', group: 'D', home: 'USA',          away: 'Paraguay',              score: '4-1', venue: 'Los Angeles Stadium', status: 'FT' },
]

export const UPCOMING = [
  { date: 'Jun 13', group: 'B', home: 'Qatar',        away: 'Switzerland',    venue: 'San Francisco Bay Area Stadium', time: '19:00' },
  { date: 'Jun 13', group: 'C', home: 'Brazil',       away: 'Morocco',        venue: 'New York/New Jersey Stadium',   time: '22:00' },
  { date: 'Jun 14', group: 'C', home: 'Haiti',        away: 'Scotland',       venue: 'Boston Stadium',                time: '01:00' },
  { date: 'Jun 14', group: 'D', home: 'Australia',    away: 'Türkiye',        venue: 'BC Place Vancouver',            time: '01:00' },
  { date: 'Jun 14', group: 'E', home: 'Germany',      away: 'Curaçao',        venue: 'Houston Stadium',               time: '13:00' },
  { date: 'Jun 14', group: 'F', home: 'Netherlands',  away: 'Japan',          venue: 'Dallas Stadium',                time: '16:00' },
  { date: 'Jun 14', group: 'E', home: 'Ivory Coast',  away: 'Ecuador',        venue: 'Philadelphia Stadium',          time: '19:00' },
  { date: 'Jun 14', group: 'F', home: 'Sweden',       away: 'Tunisia',        venue: 'Estadio Monterrey',             time: '22:00' },
  { date: 'Jun 15', group: 'H', home: 'Spain',        away: 'Cape Verde',     venue: 'Atlanta Stadium',               time: '13:00' },
  { date: 'Jun 15', group: 'G', home: 'Belgium',      away: 'Egypt',          venue: 'Seattle Stadium',               time: '18:00' },
  { date: 'Jun 15', group: 'H', home: 'Saudi Arabia', away: 'Uruguay',        venue: 'Miami Stadium',                 time: '18:00' },
  { date: 'Jun 15', group: 'G', home: 'Iran',         away: 'New Zealand',    venue: 'Los Angeles Stadium',           time: '21:00' },
  { date: 'Jun 16', group: 'I', home: 'France',       away: 'Iraq',           venue: 'Dallas Stadium',                time: '13:00' },
  { date: 'Jun 16', group: 'J', home: 'Argentina',    away: 'Algeria',        venue: 'Philadelphia Stadium',          time: '16:00' },
  { date: 'Jun 16', group: 'I', home: 'Norway',       away: 'Senegal',        venue: 'Kansas City Stadium',           time: '19:00' },
  { date: 'Jun 16', group: 'J', home: 'Austria',      away: 'Jordan',         venue: 'Houston Stadium',               time: '22:00' },
  { date: 'Jun 17', group: 'K', home: 'Portugal',     away: 'Uzbekistan',     venue: 'New York/New Jersey Stadium',   time: '13:00' },
  { date: 'Jun 17', group: 'L', home: 'England',      away: 'Ghana',          venue: 'Boston Stadium',                time: '16:00' },
  { date: 'Jun 17', group: 'K', home: 'Colombia',     away: 'DR Congo',       venue: 'Miami Stadium',                 time: '19:00' },
  { date: 'Jun 17', group: 'L', home: 'Croatia',      away: 'Panama',         venue: 'Los Angeles Stadium',           time: '22:00' },
]

// ─── Opponent Profiles ────────────────────────────────────────────────────────

export const OPPONENTS = {
  brazil: {
    id: 'brazil',
    name: 'Brazil',
    group: 'C',
    groupTeams: ['Brazil', 'Haiti', 'Morocco', 'Scotland'],
    manager: 'Carlo Ancelotti',
    style: 'Attacking 4-2-3-1 / Wide Overloads',
    formation: '4-2-3-1',
    color: '#FFDF00',
    flag: '🇧🇷',
    fifaRank: 5,
    wcAppearances: 23,
    titles: 5,
    weaknesses: ['Defensive transition gaps', 'Full-back recovery speed', 'Set-piece vulnerability at near post'],
    strengths: ['Individual brilliance on the flanks', 'Quick combination play in half-spaces', 'Clinical finishing from Vinicius Jr'],
    stats: {
      'Press PPDA':       { value: '9.8',  rating: 'warning', label: 'Moderate-high press intensity' },
      'Defensive Line':   { value: '48m',  rating: 'warning', label: 'High line — exposed on transitions' },
      'Possession Avg':   { value: '62%',  rating: 'safe',    label: 'Dominant ball control' },
      'Chance Creation':  { value: '3.2',  rating: 'safe',    label: 'xG per 90 — elite output' },
      'xG Against':       { value: '1.14', rating: 'danger',  label: 'Concedes chances on counters' },
      'Set Piece Conv.':  { value: '16%',  rating: 'warning', label: 'Near-post vulnerability flagged' },
    },
    form: [
      { vs: 'Panama',      score: '3-1', result: 'W', date: 'May 31' },
      { vs: 'Colombia',    score: '2-2', result: 'D', date: 'Mar 25' },
      { vs: 'Uruguay',     score: '4-1', result: 'W', date: 'Nov 19' },
      { vs: 'Venezuela',   score: '1-1', result: 'D', date: 'Nov 14' },
      { vs: 'Peru',        score: '2-0', result: 'W', date: 'Oct 15' },
    ],
    players: [
      { name: 'Alisson',           pos: 'GK',  rating: 89, flag: '🇧🇷', note: 'Sweeper-keeper — aggressive distribution. Press early.' },
      { name: 'Marquinhos',        pos: 'CB',  rating: 88, flag: '🇧🇷', note: 'Experienced organiser — struggles against pace in behind' },
      { name: 'Vinicius Jr',       pos: 'LW',  rating: 93, flag: '🇧🇷', note: 'Elite dribbler, cuts inside — double up on his right foot' },
      { name: 'Raphinha',          pos: 'RW',  rating: 86, flag: '🇧🇷', note: 'Direct runner on the right — show him inside, cover cut-back' },
      { name: 'Bruno Guimarães',   pos: 'CM',  rating: 87, flag: '🇧🇷', note: 'Deep-lying playmaker — press high to deny passing lanes' },
      { name: 'Endrick',           pos: 'ST',  rating: 82, flag: '🇧🇷', note: 'Raw power and pace — CBs must not dive in, stay compact' },
      { name: 'Neymar Jr',        pos: 'CAM', rating: 84, flag: '🇧🇷', note: 'Returning from injury — fitness concern but still a creative threat' },
      { name: 'Lucas Paquetá',     pos: 'CM',  rating: 85, flag: '🇧🇷', note: 'Links midfield to attack — shuttle runs dangerous in half-spaces' },
    ],
  },

  france: {
    id: 'france',
    name: 'France',
    group: 'I',
    groupTeams: ['France', 'Iraq', 'Norway', 'Senegal'],
    manager: 'Didier Deschamps',
    style: 'Pragmatic Counter-Attack / 4-3-3',
    formation: '4-3-3',
    color: '#002395',
    flag: '🇫🇷',
    fifaRank: 2,
    wcAppearances: 17,
    titles: 2,
    weaknesses: ['Over-reliance on Mbappé', 'Slow build-up against deep blocks', 'Ageing full-back rotation'],
    strengths: ['Devastating counter-attacks', 'World-class depth at every position', 'Set-piece height advantage'],
    stats: {
      'Press PPDA':       { value: '11.2', rating: 'safe',    label: 'Moderate press — sits deeper' },
      'Defensive Line':   { value: '42m',  rating: 'safe',    label: 'Compact mid-block' },
      'Possession Avg':   { value: '56%',  rating: 'safe',    label: 'Comfortable ceding ball' },
      'Chance Creation':  { value: '2.8',  rating: 'safe',    label: 'Clinical on fewer chances' },
      'xG Against':       { value: '0.78', rating: 'safe',    label: 'Very hard to break down' },
      'Set Piece Conv.':  { value: '22%',  rating: 'warning', label: 'Aerial dominance from corners' },
    },
    form: [
      { vs: 'Croatia',     score: '1-0', result: 'W', date: 'Jun 08' },
      { vs: 'Spain',       score: '2-1', result: 'W', date: 'Jun 05' },
      { vs: 'Germany',     score: '0-0', result: 'D', date: 'Mar 23' },
      { vs: 'Italy',       score: '3-1', result: 'W', date: 'Nov 17' },
      { vs: 'Israel',      score: '1-0', result: 'W', date: 'Nov 14' },
    ],
    players: [
      { name: 'Mike Maignan',       pos: 'GK',  rating: 88, flag: '🇫🇷', note: 'Aggressive GK — sweeps well but commit him with early balls' },
      { name: 'William Saliba',     pos: 'CB',  rating: 89, flag: '🇫🇷', note: 'Dominant in the air — run at him 1v1 to force fouls' },
      { name: 'Kylian Mbappé',      pos: 'LW',  rating: 94, flag: '🇫🇷', note: 'Fastest player in tournament — never allow space in behind' },
      { name: 'Aurélien Tchouaméni',pos: 'DM',  rating: 87, flag: '🇫🇷', note: 'Pivot shield — bypass with quick 1-2s through central lane' },
      { name: 'Jules Koundé',       pos: 'RB',  rating: 86, flag: '🇫🇷', note: 'Inverted FB — leaves right channel open for overlapping runs' },
      { name: 'Ousmane Dembélé',    pos: 'RW',  rating: 85, flag: '🇫🇷', note: 'Explosive on the right — unpredictable but loses possession' },
      { name: 'Michael Olise',      pos: 'AM',  rating: 84, flag: '🇫🇷', note: 'Creative link player — man-mark to deny supply to Mbappé' },
      { name: 'Marcus Thuram',      pos: 'ST',  rating: 85, flag: '🇫🇷', note: 'Physical target man — don\'t let him hold up, press immediately' },
    ],
  },

  argentina: {
    id: 'argentina',
    name: 'Argentina',
    group: 'J',
    groupTeams: ['Argentina', 'Algeria', 'Austria', 'Jordan'],
    manager: 'Lionel Scaloni',
    style: 'Balanced 4-3-3 / Controlled Possession',
    formation: '4-3-3',
    color: '#75AADB',
    flag: '🇦🇷',
    fifaRank: 1,
    wcAppearances: 19,
    titles: 3,
    weaknesses: ['Messi fitness dependency', 'Fullback fatigue in extra time', 'Vulnerable to high-intensity press'],
    strengths: ['Tournament mentality', 'Midfield control via Mac Allister & Enzo', 'Messi\'s final-third magic'],
    stats: {
      'Press PPDA':       { value: '10.4', rating: 'safe',    label: 'Balanced press — picks moments' },
      'Defensive Line':   { value: '44m',  rating: 'safe',    label: 'Disciplined shape' },
      'Possession Avg':   { value: '58%',  rating: 'safe',    label: 'Patient build-up' },
      'Chance Creation':  { value: '2.6',  rating: 'safe',    label: 'Efficient, not wasteful' },
      'xG Against':       { value: '0.82', rating: 'safe',    label: 'Defensively solid' },
      'Set Piece Conv.':  { value: '19%',  rating: 'safe',    label: 'Modest dead-ball threat' },
    },
    form: [
      { vs: 'Iceland',     score: '3-0', result: 'W', date: 'Jun 09' },
      { vs: 'Zambia',      score: '2-0', result: 'W', date: 'Mar 31' },
      { vs: 'Bolivia',     score: '2-0', result: 'W', date: 'Mar 25' },
      { vs: 'Colombia',    score: '1-1', result: 'D', date: 'Nov 19' },
      { vs: 'Paraguay',    score: '1-0', result: 'W', date: 'Nov 14' },
    ],
    players: [
      { name: 'Emiliano Martínez', pos: 'GK',  rating: 89, flag: '🇦🇷', note: 'Penalty specialist — mind games. Elite shot-stopper' },
      { name: 'Cristian Romero',    pos: 'CB',  rating: 87, flag: '🇦🇷', note: 'Aggressive CB — draw him out with dummy runs' },
      { name: 'Lionel Messi',       pos: 'RW',  rating: 88, flag: '🇦🇷', note: 'Final World Cup — conserves energy, deadly in final third' },
      { name: 'Alexis Mac Allister',pos: 'CM',  rating: 86, flag: '🇦🇷', note: 'Press-resistant CM — close down early, deny half-turn' },
      { name: 'Enzo Fernández',     pos: 'CM',  rating: 86, flag: '🇦🇷', note: 'Progressive passer — block passing lanes to flanks' },
      { name: 'Julián Álvarez',     pos: 'ST',  rating: 87, flag: '🇦🇷', note: 'Tireless runner — drops deep, creates overloads' },
      { name: 'Lautaro Martínez',   pos: 'ST',  rating: 86, flag: '🇦🇷', note: 'Penalty-box predator — tight marking required' },
      { name: 'Nahuel Molina',      pos: 'RB',  rating: 83, flag: '🇦🇷', note: 'Overlapping threat — pin him back with wide pressure' },
    ],
  },

  spain: {
    id: 'spain',
    name: 'Spain',
    group: 'H',
    groupTeams: ['Spain', 'Cape Verde', 'Saudi Arabia', 'Uruguay'],
    manager: 'Luis de la Fuente',
    style: 'Tiki-Taka 2.0 / Aggressive 4-3-3',
    formation: '4-3-3',
    color: '#FF0000',
    flag: '🇪🇸',
    fifaRank: 3,
    wcAppearances: 17,
    titles: 1,
    weaknesses: ['Young squad — can lose focus', 'Gaps between lines when pressing high', 'Susceptible to long-ball bypasses'],
    strengths: ['Lamine Yamal\'s generational talent', 'Midfield domination', 'Relentless pressing from front'],
    stats: {
      'Press PPDA':       { value: '7.8',  rating: 'danger',  label: 'Extremely high press' },
      'Defensive Line':   { value: '54m',  rating: 'danger',  label: 'Highest line in tournament' },
      'Possession Avg':   { value: '67%',  rating: 'safe',    label: 'Total ball dominance' },
      'Chance Creation':  { value: '3.5',  rating: 'safe',    label: 'Elite creative output' },
      'xG Against':       { value: '0.96', rating: 'warning', label: 'High line creates chances against' },
      'Set Piece Conv.':  { value: '14%',  rating: 'safe',    label: 'Below average dead-ball threat' },
    },
    form: [
      { vs: 'Portugal',    score: '1-0', result: 'W', date: 'Jun 08' },
      { vs: 'France',      score: '1-2', result: 'L', date: 'Jun 05' },
      { vs: 'Netherlands', score: '3-0', result: 'W', date: 'Mar 23' },
      { vs: 'Switzerland', score: '3-2', result: 'W', date: 'Nov 18' },
      { vs: 'Denmark',     score: '1-0', result: 'W', date: 'Nov 15' },
    ],
    players: [
      { name: 'Unai Simón',        pos: 'GK',  rating: 85, flag: '🇪🇸', note: 'Good with feet — press his distribution under pressure' },
      { name: 'Lamine Yamal',      pos: 'RW',  rating: 90, flag: '🇪🇸', note: '18 y/o sensation — double team, never let him cut inside' },
      { name: 'Pedri',             pos: 'CM',  rating: 88, flag: '🇪🇸', note: 'Metronome — neutralise him and Spain\'s rhythm breaks' },
      { name: 'Rodri',             pos: 'DM',  rating: 93, flag: '🇪🇸', note: 'Best DM in the world — overload to isolate him' },
      { name: 'Dani Olmo',         pos: 'AM',  rating: 86, flag: '🇪🇸', note: 'Roaming creator — tracks back poorly, exploit space behind' },
      { name: 'Nico Williams',     pos: 'LW',  rating: 86, flag: '🇪🇸', note: 'Explosive pace on left — don\'t let him run at fullback 1v1' },
      { name: 'Marc Cucurella',    pos: 'LB',  rating: 83, flag: '🇪🇸', note: 'Adventurous LB — space behind him when he bombs forward' },
      { name: 'Álvaro Morata',     pos: 'ST',  rating: 83, flag: '🇪🇸', note: 'Captain — intelligent movement. Track near-post runs' },
    ],
  },

  england: {
    id: 'england',
    name: 'England',
    group: 'L',
    groupTeams: ['Croatia', 'England', 'Ghana', 'Panama'],
    manager: 'Thomas Tuchel',
    style: 'Structured 3-4-2-1 / Wingback System',
    formation: '3-4-2-1',
    color: '#FFFFFF',
    flag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
    fifaRank: 4,
    wcAppearances: 17,
    titles: 1,
    weaknesses: ['Slow build-up from back-3', 'Wingback gaps on transitions', 'Limited creativity without Bellingham'],
    strengths: ['Bellingham-Saka axis', 'Kane\'s holdup play', 'Defensive solidity under Tuchel'],
    stats: {
      'Press PPDA':       { value: '10.8', rating: 'safe',    label: 'Measured press — conserves energy' },
      'Defensive Line':   { value: '40m',  rating: 'safe',    label: 'Deep block — hard to break' },
      'Possession Avg':   { value: '54%',  rating: 'safe',    label: 'Pragmatic — not obsessed with ball' },
      'Chance Creation':  { value: '2.4',  rating: 'warning', label: 'Relies on individual moments' },
      'xG Against':       { value: '0.72', rating: 'safe',    label: 'Extremely hard to score against' },
      'Set Piece Conv.':  { value: '24%',  rating: 'danger',  label: 'Major set-piece threat — Stones, Kane' },
    },
    form: [
      { vs: 'Turkey',      score: '1-0', result: 'W', date: 'Jun 07' },
      { vs: 'South Korea', score: '2-1', result: 'W', date: 'Jun 03' },
      { vs: 'Italy',       score: '0-0', result: 'D', date: 'Mar 20' },
      { vs: 'Greece',      score: '3-0', result: 'W', date: 'Nov 14' },
      { vs: 'Ireland',     score: '5-0', result: 'W', date: 'Nov 17' },
    ],
    players: [
      { name: 'Jordan Pickford',  pos: 'GK',  rating: 85, flag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿', note: 'Distribution under pressure is weak — press his kicks' },
      { name: 'John Stones',      pos: 'CB',  rating: 86, flag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿', note: 'Ball-playing CB — force early passes with high press' },
      { name: 'Jude Bellingham',  pos: 'AM',  rating: 91, flag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿', note: 'Box-to-box engine — denying space between lines is critical' },
      { name: 'Harry Kane',       pos: 'ST',  rating: 89, flag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿', note: 'Drops deep — CBs must not follow, hold the line' },
      { name: 'Bukayo Saka',      pos: 'RW',  rating: 88, flag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿', note: 'Inverted winger — show him outside, deny cut inside' },
      { name: 'Declan Rice',      pos: 'DM',  rating: 88, flag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿', note: 'Carries from deep — press early before he drives forward' },
      { name: 'Kobbie Mainoo',    pos: 'CM',  rating: 82, flag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿', note: 'Young progressive passer — physical battle to unsettle' },
      { name: 'Noni Madueke',     pos: 'RW',  rating: 82, flag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿', note: 'Electric dribbler off the bench — fresh legs cause problems late' },
    ],
  },

  germany: {
    id: 'germany',
    name: 'Germany',
    group: 'E',
    groupTeams: ['Germany', 'Curaçao', 'Ivory Coast', 'Ecuador'],
    manager: 'Julian Nagelsmann',
    style: 'High Pressing 4-2-3-1 / Verticality',
    formation: '4-2-3-1',
    color: '#000000',
    flag: '🇩🇪',
    fifaRank: 8,
    wcAppearances: 20,
    titles: 4,
    weaknesses: ['Aging spine — Neuer, Rüdiger', 'Wide areas in transition', 'Inconsistent under tournament pressure'],
    strengths: ['Musiala + Wirtz creative duo', 'Aggressive press from front', 'Tactical versatility'],
    stats: {
      'Press PPDA':       { value: '8.4',  rating: 'danger',  label: 'High-intensity front press' },
      'Defensive Line':   { value: '50m',  rating: 'warning', label: 'Aggressive line — exploitable' },
      'Possession Avg':   { value: '60%',  rating: 'safe',    label: 'Dominant in qualifying' },
      'Chance Creation':  { value: '3.0',  rating: 'safe',    label: 'Creative duo is lethal' },
      'xG Against':       { value: '0.94', rating: 'warning', label: 'Concedes on counters' },
      'Set Piece Conv.':  { value: '20%',  rating: 'warning', label: 'Rüdiger & Havertz aerial threats' },
    },
    form: [
      { vs: 'USA',          score: '2-2', result: 'D', date: 'Jun 07' },
      { vs: 'Turkey',       score: '4-1', result: 'W', date: 'Jun 03' },
      { vs: 'France',       score: '0-0', result: 'D', date: 'Mar 23' },
      { vs: 'Bosnia & Herz.',score:'3-1', result: 'W', date: 'Nov 16' },
      { vs: 'Hungary',      score: '2-0', result: 'W', date: 'Nov 19' },
    ],
    players: [
      { name: 'Manuel Neuer',       pos: 'GK',  rating: 85, flag: '🇩🇪', note: 'Aging but still elite. Rushes out — chip over the top' },
      { name: 'Antonio Rüdiger',    pos: 'CB',  rating: 87, flag: '🇩🇪', note: 'Aggressive stepping — use dummy runs to pull him out' },
      { name: 'Jamal Musiala',      pos: 'AM',  rating: 90, flag: '🇩🇪', note: 'Unplayable in tight spaces — must man-mark in final third' },
      { name: 'Florian Wirtz',      pos: 'AM',  rating: 89, flag: '🇩🇪', note: 'Creative genius — deny time on the ball at all costs' },
      { name: 'Joshua Kimmich',     pos: 'RB',  rating: 87, flag: '🇩🇪', note: 'Inverted FB / DM hybrid — creates overloads centrally' },
      { name: 'Kai Havertz',        pos: 'ST',  rating: 84, flag: '🇩🇪', note: 'False 9 movement — CBs must communicate constantly' },
      { name: 'Leroy Sané',         pos: 'RW',  rating: 83, flag: '🇩🇪', note: 'Pace merchant — don\'t let him isolate your fullback' },
      { name: 'Aleksandar Pavlović',pos: 'DM',  rating: 82, flag: '🇩🇪', note: 'Young pivot — physically disrupt his passing rhythm' },
    ],
  },
}

// ─── Tactical Formations ──────────────────────────────────────────────────────

export const FORMATIONS = {
  '4-3-3': {
    label: '4-3-3 Counter Block',
    tagline: 'Compact mid-block — rapid wide transitions',
    confidence: 88,
    nodes: [
      { id: 'GK',  x: 50, y: 90, role: 'GK',  name: 'Keeper'      },
      { id: 'LB',  x: 13, y: 74, role: 'DEF', name: 'Left Back'   },
      { id: 'CB1', x: 34, y: 78, role: 'DEF', name: 'Centre Back' },
      { id: 'CB2', x: 66, y: 78, role: 'DEF', name: 'Centre Back' },
      { id: 'RB',  x: 87, y: 74, role: 'DEF', name: 'Right Back'  },
      { id: 'CM1', x: 24, y: 54, role: 'MID', name: 'Left CM'     },
      { id: 'CM2', x: 50, y: 49, role: 'MID', name: 'Pivot'       },
      { id: 'CM3', x: 76, y: 54, role: 'MID', name: 'Right CM'    },
      { id: 'LW',  x: 16, y: 28, role: 'ATT', name: 'Left Wing'   },
      { id: 'ST',  x: 50, y: 20, role: 'ATT', name: 'Striker'     },
      { id: 'RW',  x: 84, y: 28, role: 'ATT', name: 'Right Wing'  },
    ],
  },
  '3-4-3': {
    label: '3-4-3 Wide Overload',
    tagline: 'Flood wide channels, exploit high defensive lines',
    confidence: 94,
    nodes: [
      { id: 'GK',  x: 50, y: 90, role: 'GK',  name: 'Keeper'      },
      { id: 'CB1', x: 24, y: 78, role: 'DEF', name: 'Left CB'     },
      { id: 'CB2', x: 50, y: 80, role: 'DEF', name: 'Centre CB'   },
      { id: 'CB3', x: 76, y: 78, role: 'DEF', name: 'Right CB'    },
      { id: 'LWB', x: 9,  y: 58, role: 'MID', name: 'Left WB'     },
      { id: 'CM1', x: 34, y: 52, role: 'MID', name: 'Left CM'     },
      { id: 'CM2', x: 66, y: 52, role: 'MID', name: 'Right CM'    },
      { id: 'RWB', x: 91, y: 58, role: 'MID', name: 'Right WB'    },
      { id: 'LW',  x: 18, y: 26, role: 'ATT', name: 'Left Wing'   },
      { id: 'ST',  x: 50, y: 19, role: 'ATT', name: 'Striker'     },
      { id: 'RW',  x: 82, y: 26, role: 'ATT', name: 'Right Wing'  },
    ],
  },
  '5-3-2': {
    label: '5-3-2 Deep Block',
    tagline: 'Absorb pressure — spring fast on counter-attacks',
    confidence: 82,
    nodes: [
      { id: 'GK',  x: 50, y: 91, role: 'GK',  name: 'Keeper'      },
      { id: 'LWB', x: 10, y: 72, role: 'DEF', name: 'Left WB'     },
      { id: 'CB1', x: 28, y: 79, role: 'DEF', name: 'Left CB'     },
      { id: 'CB2', x: 50, y: 81, role: 'DEF', name: 'Centre CB'   },
      { id: 'CB3', x: 72, y: 79, role: 'DEF', name: 'Right CB'    },
      { id: 'RWB', x: 90, y: 72, role: 'DEF', name: 'Right WB'    },
      { id: 'CM1', x: 25, y: 54, role: 'MID', name: 'Left CM'     },
      { id: 'CM2', x: 50, y: 50, role: 'MID', name: 'Pivot'       },
      { id: 'CM3', x: 75, y: 54, role: 'MID', name: 'Right CM'    },
      { id: 'ST1', x: 35, y: 24, role: 'ATT', name: 'Striker'     },
      { id: 'ST2', x: 65, y: 24, role: 'ATT', name: 'Striker'     },
    ],
  },
  '4-4-2': {
    label: '4-4-2 Flat',
    tagline: 'Compact lines — deny space between midfield and defence',
    confidence: 76,
    nodes: [
      { id: 'GK',  x: 50, y: 91, role: 'GK',  name: 'Keeper'      },
      { id: 'LB',  x: 13, y: 74, role: 'DEF', name: 'Left Back'   },
      { id: 'CB1', x: 34, y: 78, role: 'DEF', name: 'Centre Back' },
      { id: 'CB2', x: 66, y: 78, role: 'DEF', name: 'Centre Back' },
      { id: 'RB',  x: 87, y: 74, role: 'DEF', name: 'Right Back'  },
      { id: 'LM',  x: 13, y: 52, role: 'MID', name: 'Left Mid'    },
      { id: 'CM1', x: 38, y: 50, role: 'MID', name: 'Centre Mid'  },
      { id: 'CM2', x: 62, y: 50, role: 'MID', name: 'Centre Mid'  },
      { id: 'RM',  x: 87, y: 52, role: 'MID', name: 'Right Mid'   },
      { id: 'ST1', x: 38, y: 24, role: 'ATT', name: 'Striker'     },
      { id: 'ST2', x: 62, y: 24, role: 'ATT', name: 'Striker'     },
    ],
  },
}

// ─── Foundry IQ Terminal Sequences ───────────────────────────────────────────

export const FOUNDRY_SEQUENCES = {
  brazil: [
    { delay: 0,    type: 'sys',  text: 'Foundry IQ v3.1 — FIFA World Cup 2026™ Tactical Engine' },
    { delay: 300,  type: 'sys',  text: 'Connecting to Azure AI Foundry endpoint...' },
    { delay: 700,  type: 'ok',   text: 'Agent pipeline authenticated ✓' },
    { delay: 1000, type: 'info', text: 'Loading opponent: Brazil 🇧🇷 | Group C | FIFA Rank #5' },
    { delay: 1400, type: 'data', text: 'Formation: 4-2-3-1 | Style: Attacking / Wide Overloads' },
    { delay: 1700, type: 'data', text: 'Manager: Carlo Ancelotti | 23rd WC appearance | 5× champions' },
    { delay: 2100, type: 'data', text: 'Key threats: Vinícius Jr (LW, 93 OVR), Raphinha (RW, 86 OVR)' },
    { delay: 2400, type: 'warn', text: 'Defensive line at 48m — HIGH. Transition attacks viable' },
    { delay: 2700, type: 'data', text: 'xG Against: 1.14 per 90 — concedes on counters' },
    { delay: 3000, type: 'warn', text: 'Neymar fitness flagged — partial starter, sub threat from 60\'' },
    { delay: 3400, type: 'info', text: 'Running formation matrix: 4-3-3, 3-4-3, 5-3-2, 4-4-2...' },
    { delay: 3800, type: 'data', text: 'Counter-Attack Index: 5-3-2 scored 89/100' },
    { delay: 4100, type: 'data', text: 'Wide Overload Defence: 5-3-2 scored 92/100' },
    { delay: 4400, type: 'ok',   text: 'Optimal formation: 5-3-2 Deep Block Protocol' },
    { delay: 4800, type: 'info', text: 'Generating set-piece triggers (3 embedded)...' },
    { delay: 5200, type: 'ok',   text: 'Tactical brief compiled — confidence: 82.4%' },
    { delay: 5500, type: 'sys',  text: 'Brief ready for coaching staff ■' },
  ],
  france: [
    { delay: 0,    type: 'sys',  text: 'Foundry IQ v3.1 — FIFA World Cup 2026™ Tactical Engine' },
    { delay: 300,  type: 'sys',  text: 'Connecting to Azure AI Foundry endpoint...' },
    { delay: 700,  type: 'ok',   text: 'Agent pipeline authenticated ✓' },
    { delay: 1000, type: 'info', text: 'Loading opponent: France 🇫🇷 | Group I | FIFA Rank #2' },
    { delay: 1400, type: 'data', text: 'Formation: 4-3-3 | Style: Pragmatic Counter-Attack' },
    { delay: 1700, type: 'data', text: 'Manager: Didier Deschamps | 2× WC winner (player + manager)' },
    { delay: 2100, type: 'warn', text: 'Mbappé pace rating 97 — CRITICAL: never allow space in behind' },
    { delay: 2400, type: 'data', text: 'xG Against: 0.78 per 90 — very hard to break down' },
    { delay: 2700, type: 'data', text: 'Koundé inverted FB — right channel opens 34% of possessions' },
    { delay: 3100, type: 'info', text: 'Running formation matrix: 4-3-3, 3-4-3, 5-3-2, 4-4-2...' },
    { delay: 3500, type: 'data', text: 'Channel Exploit Index: 4-3-3 scored 86/100' },
    { delay: 3800, type: 'data', text: 'Deep Block Efficiency: 4-3-3 scored 91/100' },
    { delay: 4200, type: 'ok',   text: 'Optimal formation: 4-3-3 Counter Block' },
    { delay: 4600, type: 'info', text: 'Generating set-piece triggers (4 embedded)...' },
    { delay: 5000, type: 'ok',   text: 'Tactical brief compiled — confidence: 88.1%' },
    { delay: 5300, type: 'sys',  text: 'Brief ready for coaching staff ■' },
  ],
  argentina: [
    { delay: 0,    type: 'sys',  text: 'Foundry IQ v3.1 — FIFA World Cup 2026™ Tactical Engine' },
    { delay: 300,  type: 'sys',  text: 'Connecting to Azure AI Foundry endpoint...' },
    { delay: 700,  type: 'ok',   text: 'Agent pipeline authenticated ✓' },
    { delay: 1000, type: 'info', text: 'Loading opponent: Argentina 🇦🇷 | Group J | FIFA Rank #1 | Defending Champions' },
    { delay: 1400, type: 'data', text: 'Formation: 4-3-3 | Style: Balanced / Controlled Possession' },
    { delay: 1700, type: 'data', text: 'Manager: Lionel Scaloni | Won WC 2022, Copa América 2024' },
    { delay: 2100, type: 'warn', text: 'Messi (38) — final World Cup. Limited minutes but lethal impact' },
    { delay: 2400, type: 'data', text: 'Midfield axis: Mac Allister + Enzo Fernández control tempo' },
    { delay: 2700, type: 'data', text: 'Tournament mentality: 3 consecutive finals (WC22, CA24, CA25)' },
    { delay: 3100, type: 'info', text: 'Running formation matrix: 4-3-3, 3-4-3, 4-4-2...' },
    { delay: 3500, type: 'data', text: 'High Press Disruption: 4-3-3 scored 84/100' },
    { delay: 3800, type: 'data', text: 'Midfield Control: 4-4-2 scored 88/100' },
    { delay: 4200, type: 'ok',   text: 'Optimal formation: 4-4-2 Compact — mirror their midfield' },
    { delay: 4600, type: 'info', text: 'Generating set-piece triggers (3 embedded)...' },
    { delay: 5000, type: 'ok',   text: 'Tactical brief compiled — confidence: 76.3%' },
    { delay: 5300, type: 'sys',  text: 'Brief ready for coaching staff ■' },
  ],
  spain: [
    { delay: 0,    type: 'sys',  text: 'Foundry IQ v3.1 — FIFA World Cup 2026™ Tactical Engine' },
    { delay: 300,  type: 'sys',  text: 'Connecting to Azure AI Foundry endpoint...' },
    { delay: 700,  type: 'ok',   text: 'Agent pipeline authenticated ✓' },
    { delay: 1000, type: 'info', text: 'Loading opponent: Spain 🇪🇸 | Group H | FIFA Rank #3 | Euro 2024 Champions' },
    { delay: 1400, type: 'data', text: 'Formation: 4-3-3 | Style: Tiki-Taka 2.0 / Aggressive Press' },
    { delay: 1700, type: 'data', text: 'PPDA: 7.8 — EXTREME press intensity. Highest in tournament.' },
    { delay: 2100, type: 'warn', text: 'Lamine Yamal (18) — generational talent. CRITICAL threat.' },
    { delay: 2400, type: 'data', text: 'Defensive line at 54m — HIGHEST in World Cup. Direct balls effective.' },
    { delay: 2700, type: 'data', text: 'Rodri (DM, 93 OVR) — best midfielder in the world. Must isolate.' },
    { delay: 3100, type: 'info', text: 'Running formation matrix: 4-3-3, 3-4-3, 5-3-2, 4-4-2...' },
    { delay: 3500, type: 'data', text: 'Line Exploit Index: 3-4-3 scored 94/100' },
    { delay: 3800, type: 'data', text: 'Wide Channel Attack: 3-4-3 scored 91/100' },
    { delay: 4200, type: 'ok',   text: 'Optimal formation: 3-4-3 Wide Overload Protocol' },
    { delay: 4600, type: 'info', text: 'Generating set-piece triggers (3 embedded)...' },
    { delay: 5000, type: 'ok',   text: 'Tactical brief compiled — confidence: 94.0%' },
    { delay: 5300, type: 'sys',  text: 'Brief ready for coaching staff ■' },
  ],
  england: [
    { delay: 0,    type: 'sys',  text: 'Foundry IQ v3.1 — FIFA World Cup 2026™ Tactical Engine' },
    { delay: 300,  type: 'sys',  text: 'Connecting to Azure AI Foundry endpoint...' },
    { delay: 700,  type: 'ok',   text: 'Agent pipeline authenticated ✓' },
    { delay: 1000, type: 'info', text: 'Loading opponent: England 🏴󠁧󠁢󠁥󠁮󠁧󠁿 | Group L | FIFA Rank #4' },
    { delay: 1400, type: 'data', text: 'Formation: 3-4-2-1 | Style: Structured / Wingback System' },
    { delay: 1700, type: 'data', text: 'Manager: Thomas Tuchel | xG Against 0.72 — elite defence' },
    { delay: 2100, type: 'warn', text: 'Set-piece conversion 24% — MAJOR threat from corners/FKs' },
    { delay: 2400, type: 'data', text: 'Bellingham (AM, 91 OVR) — engine of all creativity' },
    { delay: 2700, type: 'data', text: 'Kane drops deep — creates 2v1 overloads in half-spaces' },
    { delay: 3100, type: 'info', text: 'Running formation matrix: 4-3-3, 3-4-3, 4-4-2...' },
    { delay: 3500, type: 'data', text: 'Midfield Overload: 4-3-3 scored 87/100' },
    { delay: 3800, type: 'data', text: 'Counter-Attack Potential: 4-3-3 scored 85/100' },
    { delay: 4200, type: 'ok',   text: 'Optimal formation: 4-3-3 Counter Block' },
    { delay: 4600, type: 'info', text: 'Generating set-piece triggers (5 embedded)...' },
    { delay: 5000, type: 'ok',   text: 'Tactical brief compiled — confidence: 88.0%' },
    { delay: 5300, type: 'sys',  text: 'Brief ready for coaching staff ■' },
  ],
  germany: [
    { delay: 0,    type: 'sys',  text: 'Foundry IQ v3.1 — FIFA World Cup 2026™ Tactical Engine' },
    { delay: 300,  type: 'sys',  text: 'Connecting to Azure AI Foundry endpoint...' },
    { delay: 700,  type: 'ok',   text: 'Agent pipeline authenticated ✓' },
    { delay: 1000, type: 'info', text: 'Loading opponent: Germany 🇩🇪 | Group E | FIFA Rank #8' },
    { delay: 1400, type: 'data', text: 'Formation: 4-2-3-1 | Style: High Press / Verticality' },
    { delay: 1700, type: 'data', text: 'Musiala + Wirtz: combined 43 G+A in 2025/26 season' },
    { delay: 2100, type: 'warn', text: 'High line at 50m — direct balls over the top effective' },
    { delay: 2400, type: 'data', text: 'Kimmich hybrid role creates overloads — track his movement' },
    { delay: 2700, type: 'data', text: 'xG Against: 0.94 — concedes on fast transitions' },
    { delay: 3100, type: 'info', text: 'Running formation matrix: 4-3-3, 3-4-3, 5-3-2, 4-4-2...' },
    { delay: 3500, type: 'data', text: 'Counter-Attack Index: 4-3-3 scored 88/100' },
    { delay: 3800, type: 'data', text: 'Press Resistance: 4-3-3 scored 84/100' },
    { delay: 4200, type: 'ok',   text: 'Optimal formation: 4-3-3 Counter Block' },
    { delay: 4600, type: 'info', text: 'Generating set-piece triggers (3 embedded)...' },
    { delay: 5000, type: 'ok',   text: 'Tactical brief compiled — confidence: 88.0%' },
    { delay: 5300, type: 'sys',  text: 'Brief ready for coaching staff ■' },
  ],
}

// ─── Recommended formation per opponent ───────────────────────────────────────

export const RECOMMENDED_FORMATION = {
  brazil:    '5-3-2',
  france:    '4-3-3',
  argentina: '4-4-2',
  spain:     '3-4-3',
  england:   '4-3-3',
  germany:   '4-3-3',
}

// ─── Reasoning Steps ──────────────────────────────────────────────────────────

export const REASONING_STEPS = {
  brazil: [
    { phase: 'Data Ingestion',      color: 'cyan',    title: 'Foundry IQ — Brazil Profile Loaded', detail: 'Ingested Brazil\'s last 14 match datasets across CONMEBOL qualifiers and friendlies. Identified 4-2-3-1 formation, 62% avg possession, and defensive line at 48m. Flagged wide-channel exposure from overlapping fullbacks as primary exploit vector.' },
    { phase: 'Pattern Recognition',  color: 'violet',  title: 'Transition Vulnerability Mapped', detail: 'Brazil\'s xG Against of 1.14 is the highest among World Cup favourites. When Vinícius Jr and Raphinha push high, the full-backs advance 8–12m beyond the halfway line, leaving 20m+ transition corridors. Agent identified 4 high-probability counter-attack lanes.' },
    { phase: 'Player Threat',        color: 'rose',    title: 'Vinícius Jr Neutralisation Plan', detail: 'Vinícius Jr (93 OVR) completes 6.2 dribbles per 90 and cuts inside 73% of the time. Counter: deploy RWB + RCB double-team, show him outside, deny cut-back pass to Paquetá in the half-space. Neymar fitness at 60% — likely sub from 60th minute.' },
    { phase: 'Formation Synthesis',  color: 'amber',   title: 'Counter-Formation: 5-3-2 Deep Block', detail: 'Evaluated 4-3-3, 3-4-3, 5-3-2, and 4-4-2 against exploit profile. 5-3-2 scored highest on Counter-Attack Index (89/100) and Wide Defence (92/100). Three CBs cover Vinícius-Raphinha width; WBs spring forward on turnover within 5 seconds.' },
    { phase: 'Tactical Output',      color: 'emerald',  title: 'Brief Finalised — 82.4% Confidence', detail: 'Final brief: (1) Compact 5-3-2 absorbs pressure in low block, (2) WBs release on counter within 5 seconds of turnover, (3) Two STs press Brazil\'s split CBs to force long balls. Confidence 82.4% — lower due to Brazil\'s individual quality ceiling.' },
  ],
  france: [
    { phase: 'Data Ingestion',      color: 'cyan',    title: 'Foundry IQ — France Profile Loaded', detail: 'Ingested France\'s tournament record: 2 World Cup titles, finalist twice. Current squad features Mbappé (94 OVR), Saliba, Tchouaméni. Formation lock: 4-3-3. xG Against of 0.78 — the most defensively solid team in the tournament.' },
    { phase: 'Pattern Recognition',  color: 'violet',  title: 'Koundé Channel Exploitation', detail: 'Jules Koundé plays as an inverted full-back, tucking inside 34% of possessions. This creates a 15m pocket on France\'s right channel that can be attacked with overlapping runs. Agent identified this as the primary entry point for crosses.' },
    { phase: 'Player Threat',        color: 'rose',    title: 'Mbappé Containment Protocol', detail: 'Mbappé\'s pace (97 sprint speed) makes him the fastest player in the tournament. He receives 4.2 progressive passes per 90 in behind the defence. Counter: NEVER play a high line. Sit at 38m depth, deny space, and force France to play through a congested midfield.' },
    { phase: 'Formation Synthesis',  color: 'amber',   title: 'Counter-Formation: 4-3-3 Counter Block', detail: '4-3-3 Counter Block scored 91/100 on Deep Block Efficiency and 86/100 on Channel Exploit. Compact mid-block denies Mbappé space; wingers positioned to exploit Koundé\'s inverted positioning on transitions.' },
    { phase: 'Tactical Output',      color: 'emerald',  title: 'Brief Finalised — 88.1% Confidence', detail: 'Final brief: (1) Low block at 38m, (2) LW positioned to attack Koundé\'s channel, (3) Press Olise to deny supply line to Mbappé, (4) Set-piece package targeting Saliba\'s blind side. Confidence 88.1%.' },
  ],
  argentina: [
    { phase: 'Data Ingestion',      color: 'cyan',    title: 'Foundry IQ — Argentina Profile Loaded', detail: 'Defending champions. Ingested 3 consecutive final runs (WC 2022, Copa 2024, Copa 2025). Scaloni\'s 4-3-3 is the most tactically flexible system in the tournament. Midfield axis of Mac Allister and Enzo Fernández controls 58% possession.' },
    { phase: 'Pattern Recognition',  color: 'violet',  title: 'Messi Dependency Analysis', detail: 'At 38, Messi conserves energy — his sprint distance dropped 22% from 2022. But he still creates 2.8 chances per 90 in the final third. When Messi is on the pitch, Argentina\'s xG creation rises 40%. Counter: let him have the ball in deep zones, block final-third entry.' },
    { phase: 'Player Threat',        color: 'rose',    title: 'Álvarez Deep Drops Create Overloads', detail: 'Julián Álvarez drops into midfield 4.1 times per 90, creating numerical overloads. This pulls CBs forward and opens space for Molina\'s overlapping runs. Counter: hold defensive line, let Álvarez have the ball in front of the back four, don\'t follow him deep.' },
    { phase: 'Formation Synthesis',  color: 'amber',   title: 'Counter-Formation: 4-4-2 Compact', detail: '4-4-2 Compact scored 88/100 on Midfield Control — matching Argentina\'s 3-man midfield with a 4-man block. Two strikers press Romero-Otamendi, forcing rushed distribution. Flat midfield 4 denies half-spaces where Messi operates.' },
    { phase: 'Tactical Output',      color: 'emerald',  title: 'Brief Finalised — 76.3% Confidence', detail: 'Final brief: (1) 4-4-2 mid-block mirrors Argentina\'s shape, (2) Two STs press split CBs, (3) Flat 4 denies Messi\'s half-space zones. Confidence 76.3% — lower score reflects Argentina\'s tournament pedigree and adaptability.' },
  ],
  spain: [
    { phase: 'Data Ingestion',      color: 'cyan',    title: 'Foundry IQ — Spain Profile Loaded', detail: 'Euro 2024 champions. Ingested Spain\'s tactical evolution under de la Fuente: PPDA of 7.8 (highest in the tournament), defensive line at 54m (highest in the World Cup), 67% average possession. Identified Lamine Yamal (18) as generational talent.' },
    { phase: 'Pattern Recognition',  color: 'violet',  title: 'Ultra-High Line Exploit Mapped', detail: 'Spain\'s 54m defensive line is the highest at the 2026 World Cup. This creates 25–30m of space behind the back four. Direct balls over the top bypass their press entirely. xG Against of 0.96 confirms opponents DO create chances when they bypass the press.' },
    { phase: 'Player Threat',        color: 'rose',    title: 'Yamal + Nico Williams Dual Threat', detail: 'Yamal (RW, 90 OVR) and Nico Williams (LW, 86 OVR) are the most explosive wing pairing in football. They complete a combined 9.4 dribbles per 90. Counter: 3-4-3 wide overload provides an extra defender on each flank to double up.' },
    { phase: 'Formation Synthesis',  color: 'amber',   title: 'Counter-Formation: 3-4-3 Wide Overload', detail: '3-4-3 scored 94/100 on Line Exploit Index — WBs positioned to surge into the 25m corridor behind Spain\'s high line within 4 seconds of winning the ball. Three ATTs occupy Spain\'s back four, preventing them from stepping forward.' },
    { phase: 'Tactical Output',      color: 'emerald',  title: 'Brief Finalised — 94.0% Confidence', detail: 'Final brief: (1) 3-CB block absorbs Yamal + Williams, (2) Direct balls over high line target WBs sprinting into channel, (3) Rodri isolation plan — overload his zone with 3 CMs. Confidence 94.0% — highest-rated brief in World Cup cycle.' },
  ],
  england: [
    { phase: 'Data Ingestion',      color: 'cyan',    title: 'Foundry IQ — England Profile Loaded', detail: 'Tuchel\'s 3-4-2-1 has made England the hardest team to score against: xG Against of 0.72 per 90. Set-piece conversion of 24% is the highest threat in the tournament. Kane, Stones, and Guehi all attack corners.' },
    { phase: 'Pattern Recognition',  color: 'violet',  title: 'Wingback Transition Gaps', detail: 'England\'s wingback system creates gaps during attacking phases. When Livramento and Spence push high, a 3v3 situation develops in defence. Transitions within 6 seconds can exploit this before wingbacks recover.' },
    { phase: 'Player Threat',        color: 'rose',    title: 'Bellingham Box-to-Box Dominance', detail: 'Jude Bellingham (91 OVR) covers 12.8km per 90 and creates 3.1 chances per match. He operates in the zone between midfield and attack. Counter: man-mark with a dedicated midfielder; deny him the half-turn.' },
    { phase: 'Formation Synthesis',  color: 'amber',   title: 'Counter-Formation: 4-3-3 Counter Block', detail: '4-3-3 scored 87/100 on Midfield Overload — the extra man in midfield vs England\'s 2-man pivot creates numerical superiority. Counter-attack potential scored 85/100, exploiting wingback recovery gaps.' },
    { phase: 'Tactical Output',      color: 'emerald',  title: 'Brief Finalised — 88.0% Confidence', detail: 'Final brief: (1) 4-3-3 with dedicated Bellingham marker, (2) Quick counters exploit wingback gaps, (3) Set-piece defensive plan: zonal near-post, man-mark Kane and Stones. Confidence 88.0%.' },
  ],
  germany: [
    { phase: 'Data Ingestion',      color: 'cyan',    title: 'Foundry IQ — Germany Profile Loaded', detail: 'Nagelsmann\'s 4-2-3-1 features the Musiala-Wirtz axis — the most creative pairing in the tournament with a combined 43 G+A in 2025/26. PPDA of 8.4 indicates a high-intensity front press. High line at 50m is exploitable.' },
    { phase: 'Pattern Recognition',  color: 'violet',  title: 'Kimmich Hybrid Role Creates Gaps', detail: 'Kimmich operates as an inverted RB, moving into central midfield 40% of the time. This creates a 2v1 overload centrally but leaves the right channel open. Agent identified 3 transition corridors when Kimmich is caught centrally.' },
    { phase: 'Player Threat',        color: 'rose',    title: 'Musiala-Wirtz Dual Playmaker Threat', detail: 'Musiala (90 OVR) operates in tight spaces; Wirtz (89 OVR) plays the killer pass. Together they create 5.6 chances per 90. Counter: compact midfield block between 35–50m, deny space between the lines. Press trigger: Pavlović\'s first touch.' },
    { phase: 'Formation Synthesis',  color: 'amber',   title: 'Counter-Formation: 4-3-3 Counter Block', detail: '4-3-3 scored 88/100 on Counter-Attack Index — rapid transitions through the channels Kimmich vacates. Press Resistance scored 84/100. Three CMs can match Germany\'s Pavlović-Goretzka pivot with numerical superiority.' },
    { phase: 'Tactical Output',      color: 'emerald',  title: 'Brief Finalised — 88.0% Confidence', detail: 'Final brief: (1) Mid-block at 42m to deny Musiala-Wirtz space, (2) LW attacks Kimmich\'s vacated right channel, (3) Press trigger on Pavlović — force errors in build-up. Confidence 88.0%.' },
  ],
}

// ─── Role Colours ─────────────────────────────────────────────────────────────

export const ROLE_COLORS = {
  GK:  { bg: 'bg-amber-400',   border: 'border-amber-200',   text: 'text-amber-950',   glow: 'shadow-amber-400/40'   },
  DEF: { bg: 'bg-blue-500',    border: 'border-blue-300',    text: 'text-blue-950',    glow: 'shadow-blue-500/40'    },
  MID: { bg: 'bg-emerald-500', border: 'border-emerald-300', text: 'text-emerald-950', glow: 'shadow-emerald-500/40' },
  ATT: { bg: 'bg-rose-500',    border: 'border-rose-300',    text: 'text-rose-950',    glow: 'shadow-rose-500/40'    },
}

// ─── Step Accent Tokens ───────────────────────────────────────────────────────

export const STEP_ACCENTS = {
  cyan:    { dot: 'bg-cyan-500',    badge: 'bg-cyan-500/10 text-cyan-400 border border-cyan-500/20',    line: 'bg-cyan-500/20'    },
  violet:  { dot: 'bg-violet-500',  badge: 'bg-violet-500/10 text-violet-400 border border-violet-500/20',  line: 'bg-violet-500/20'  },
  amber:   { dot: 'bg-amber-500',   badge: 'bg-amber-500/10 text-amber-400 border border-amber-500/20',   line: 'bg-amber-500/20'   },
  rose:    { dot: 'bg-rose-500',    badge: 'bg-rose-500/10 text-rose-400 border border-rose-500/20',    line: 'bg-rose-500/20'    },
  emerald: { dot: 'bg-emerald-500', badge: 'bg-emerald-500/10 text-emerald-400 border border-emerald-500/20', line: 'bg-emerald-500/20' },
}
